twig:
    file_name_pattern: '*.twig'
#    form_themes: ['tailwind_2_layout.html.twig']
    form_themes:
       - '@TalesFromADevFlowbite/form/default.html.twig'

when@test:
    twig:
        strict_variables: true
