vich_uploader:
    db_driver: orm

    mappings:
        courses:
            uri_prefix: /images/courses
            upload_destination: '%kernel.project_dir%/assets/images/courses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        programs:
            uri_prefix: /programs
            upload_destination: '%kernel.project_dir%/assets/programs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        users:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/assets/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        news:
            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/assets/images/news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer